config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  resources :products, only: [:index, :show] do
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  resource :cart
  resources :orders do
    post :checkout_spgateway, on: :member
  end

  namespace :admin do
    root "products#index"
    resources :products
    resources :orders
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller_name %>_<%= action_name %>">
    <header>
      <div class="container">
        <div id="logo">
          <%= link_to root_path do %>
            <img src="http://via.placeholder.com/80x40">
          <% end %>
        </div>
        <ul class="nav">
          <% if current_user.role == "admin" %>
            <span><%= current_user.email %></span>
            <li><%= link_to "Products", admin_products_path %></li>
            <li><%= link_to "Orders", admin_orders_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </header>

    <section id="content">
      <div class="container">
        <% if notice %>
          <div class="notice"><%= notice %></div>
        <% end %>

        <% if alert %>
          <div class="alert"><%= alert %></div>
        <% end %>

        <%= yield %>
      </div>
    </section>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller_name %>_<%= action_name %>">
    <header>
      <div class="container">
        <div id="logo">
          <%= link_to root_path do %>
            <img src="http://via.placeholder.com/80x40">
          <% end %>
        </div>
        <ul class="nav">
          <% if current_user %>
            <span><%= current_user.email %></span>
            <li><%= link_to "Admin", admin_root_path if current_user.admin? %></li>
            <li><%= link_to "Cart", cart_path %></li>
            <li><%= link_to "Order", orders_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </header>

    <section id="content">
      <div class="container">
        <% if notice %>
          <div class="notice"><%= notice %></div>
        <% end %>

        <% if alert %>
          <div class="alert"><%= alert %></div>
        <% end %>

        <%= yield %>
      </div>
    </section>

  </body>
</html>